import Head from "next/head";
import Image from "next/image";
import { trpc } from "../src/trpcUtil";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data } = trpc.hello.useQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the tRPC/NextJS bug demo.</h1>

        <p>There should be JSON data below:</p>

        <pre>{data ? JSON.stringify(data, null, 2) : undefined}</pre>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps = () => {
  return {
    props: {},
    revalidate: 1,
  };
};
